on: [push, pull_request, workflow_dispatch]

jobs:
  zmk_build:
    working-directory: zmk-config
    steps:
      - name: Build User Config
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

